---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hello-caddy
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/mkahric/k3s-fluxcd-kustomize
